### ISSUE TITLE
cleansimple.ca/job no longer accessable

### ISSUE THREAD

**Issue by mcoopercleansimple** [VyomParashar/cleanjobs#1]
@VyomParashar Looks like the site is no longer accessible.  Just wanted to log this as a new issue.

**Comment by VyomParashar** [comment]
Which part is not accessible please....

**Comment by VyomParashar** [comment]
Just checked, but look like working

**Comment by mcoopercleansimple** [comment]
I get the attached message
<img width="1275" alt="screen shot 2016-02-21 at 8 38 04 am" src="https://cloud.githubusercontent.com/assets/16672728/13202591/79cd35f2-d876-11e5-95e9-9528865e0287.png">

**Comment by VyomParashar** [comment]
Okay you are logged in to admin section... fixing... sec.

**Comment by VyomParashar** [comment]
Should be fixed now

**Comment by mcoopercleansimple** [comment]
Looks good
